# Site settings
title: Fotis Alexandrou
email: alfotis@yahoo.gr
description: "Tales of a web developer"
baseurl: ""
url: "http://falexandrou.com"
twitter_username: falexandrou
github_username:  falexandrou
facebook_username:  falexandrou

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]
