# Site settings
title: Fotis Alexandrou
email: alfotis@yahoo.gr
description: "Tales of a Web Developer"
baseurl: ""
url: "http://www.falexandrou.com"
twitter_username: falexandrou
github_username:  falexandrou
facebook_username:  falexandrou
linkedin_profile: http://gr.linkedin.com/in/falexandrou
google_analytics: "UA-649986-28"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 15
exclude: ["node_modules"]

# Plugins
gems: [ "pygments.rb", "jekyll-mentions", "jekyll-sitemap", "jemoji" ]
